spring:
  datasource:
    url: jdbc:mysql://localhost:3306/teste?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    username: root
    password: 123Aa321
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true